name: icesat2-hackweek
channels:
  - conda-forge/label/broken
  - conda-forge
  - defaults
dependencies:
  - adal=1.2.1
  - affine=2.2.2
  - appdirs=1.4.3
  - asciitree=0.3.3
  - asn1crypto=0.24.0
  - astropy=3.2
  - atomicwrites=1.3.0
  - attrs=18.2.0
  - awscli=1.16.179
  - backcall=0.1.0
  - basemap=1.2.0
  - bcrypt=3.1.6
  - blas=2.7
  - bleach=3.1.0
  - blinker=1.4
  - bokeh=1.2.0
  - boost-cpp=1.70.0
  - boto3=1.9.169
  - botocore=1.12.169
  - branca=0.3.1
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cachetools=2.1.0
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.3.9
  - cffi=1.12.3
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.1
  - colorama=0.3.9
  - colorcet=2.0.1
  - conda=4.6.14
  - conda-env=2.6.0
  - contextily=0.9.2
  - cryptography=2.7
  - curl=7.64.1
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=1.1.1
  - dask-core=1.1.1
  - dask-kubernetes=0.8.0
  - datashader=0.6.9
  - datashape=0.5.4
  - decorator=4.3.2
  - defusedxml=0.5.0
  - descartes=1.1.0
  - distributed=1.25.3
  - docutils=0.14
  - entrypoints=0.3
  - expat=2.2.5
  - fasteners=0.14.1
  - fiona=1.8.6
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - gcsfs=0.2.2
  - gdal=2.4.1
  - geopandas=0.5.0
  - geos=3.7.1
  - geotiff=1.4.3
  - geoviews-core=1.6.2
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.58.3
  - gmp=6.1.2
  - google-auth=1.6.3
  - google-auth-oauthlib=0.4.0
  - graphite2=1.3.13
  - graphviz=2.38.0
  - h5netcdf=0.7.4
  - h5py=2.9.0
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.0
  - holoviews=1.12.3
  - hvplot=0.4.0
  - icu=58.2
  - idna=2.8
  - imageio=2.5.0
  - importlib_metadata=0.18
  - intake=0.4.4
  - intake-xarray=0.3.0
  - ipykernel=5.1.1
  - ipyleaflet=0.10.4
  - ipympl=0.2.1
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.2
  - jinja2=2.10
  - jmespath=0.9.4
  - joblib=0.13.2
  - jpeg=9c
  - json-c=0.13.1
  - jsonschema=3.0.0a3
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - jupyterlab=0.35.6
  - jupyterlab_launcher=0.13.1
  - jupyterlab_server=0.2.0
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libdap4=3.19.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=2.4.1
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libpq=11.3
  - libsodium=1.0.16
  - libspatialindex=1.9.0
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.32
  - llvmlite=0.28.0
  - locket=0.2.0
  - lxml=4.3.4
  - lz4-c=1.8.3
  - mapclassify=2.0.1
  - markupsafe=1.1.0
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - mercantile=1.0.4
  - mistune=0.8.4
  - monotonic=1.5
  - more-itertools=4.3.0
  - msgpack-numpy=0.4.4.3
  - msgpack-python=0.6.1
  - multipledispatch=0.6.0
  - munch=2.3.2
  - nb_conda_kernels=2.2.2
  - nbconvert=5.4.0
  - nbformat=4.4.0
  - nbserverproxy=0.8.8
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - networkx=2.3
  - nomkl=3.0
  - notebook=5.7.8
  - numba=0.43.1
  - numcodecs=0.6.3
  - numpy=1.16.4
  - oauthlib=3.0.1
  - olefile=0.46
  - openblas=0.3.5
  - openjpeg=2.3.1
  - openssl=1.1.1b
  - owslib=0.17.1
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=1.19.2
  - pandocfilters=1.4.2
  - pango=1.40.14
  - param=1.9.1
  - paramiko=2.5.0
  - parso=0.3.3
  - partd=0.3.10
  - patsy=0.5.1
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1.1
  - pixman=0.34.0
  - pluggy=0.12.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.3
  - proj4=5.2.0
  - prometheus_client=0.5.0
  - prompt_toolkit=2.0.8
  - psutil=5.6.3
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.8.0
  - pyasn1=0.4.5
  - pyasn1-modules=0.2.5
  - pycosat=0.6.3
  - pycparser=2.19
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pyepsg=0.4.0
  - pygments=2.3.1
  - pyjwt=1.7.1
  - pykdtree=1.3.1
  - pynacl=1.3.0
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyproj=1.9.6
  - pyrsistent=0.14.10
  - pyshp=2.1.0
  - pysocks=1.7.0
  - pytest=4.6.3
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.3.0
  - pytest-openfiles=0.3.1
  - pytest-remotedata=0.3.1
  - python=3.6.7
  - python-kubernetes=9.0.0
  - python-snappy=0.5.4
  - pytz=2019.1
  - pyviz_comms=0.7.2
  - pywavelets=1.0.3
  - pyyaml=5.1
  - pyzmq=17.1.2
  - qtconsole=4.5.1
  - rasterio=1.0.24
  - readline=7.0
  - requests=2.21.0
  - requests-oauthlib=1.2.0
  - rsa=3.4.2
  - rtree=0.8.3
  - ruamel=1.0
  - ruamel.yaml=0.15.96
  - ruamel_yaml=0.15.71
  - s3fs=0.2.1
  - s3transfer=0.2.1
  - scikit-image=0.15.0
  - scipy=1.3.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=40.8.0
  - shapely=1.6.4
  - sip=4.18
  - six=1.12.0
  - snappy=1.1.7
  - snuggs=1.4.6
  - sortedcontainers=2.1.0
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - tblib=1.4.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=5.1.1
  - traitlets=4.3.2
  - traittypes=0.2.1
  - tzcode=2019a
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - websocket-client=0.56.0
  - wheel=0.32.3
  - widgetsnbextension=3.4.2
  - xarray=0.12.1
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zarr=2.2.0
  - zeromq=4.2.5
  - zict=0.1.4
  - zipp=0.5.1
  - zlib=1.2.11
  - zstd=1.4.0
  - pip:
    - alembic==1.0.7
    - async-generator==1.10
    - dask-labextension==0.3.1
    - jupyterhub==0.9.4
    - mako==1.0.7
    - matplotlib-scalebar==0.5.1
    - nbgitpuller==0.6.1
    - nteract-on-jupyter==2.0.0
    - pamela==1.0.0
    - python-dateutil==2.7.5
    - python-editor==1.0.4
    - python-oauth2==1.1.0
    - rio-cogeo==1.0.0
    - sat-search==0.2.0
    - sat-stac==0.1.3
    - sqlalchemy==1.2.17
    - supermercado==0.0.5
    - urllib3==1.24.1
